## Unzip the downloaded zip folder and read the txt file
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings ="?", stringsAsFactors = FALSE)
library(dplyr)
data2 <- filter(data, Date == "1/2/2007" | Date == "2/2/2007")
Date <- as.vector(data2$Date)
Time <- as.vector(data2$Time)
x <- paste(Date, Time)
mergedTime <- strptime(x, "%d/%m/%Y %H:%M:%S")
data3 <- cbind(data2, mergedTime)
png(filename = "plot2.png", bg = "transparent")
with(data3, plot(mergedTime, Global_active_power, xlab = NA, ylab = "Global Active Power (kilowatts)", pch = NA))
lines(data3$mergedTime, data3$Global_active_power)
dev.off()
